### PR TITLE
Add spotlight article on Kubernetes Contributor Summit

### PR DESCRIPTION
**Pull request by fsmunoz**
Add spotlight article on the Kubernetes Contributor Summit, using KCSEU2023 as the main example.

Closes: #448

### CODE REVIEW

**Comment by jberkus** [comment]
Seems fine, unless we want to add feedback from other KCS leads?

**Comment by fsmunoz** [comment]
@jberkus that would be good, yes. I did approach it as a 1:1 interview (similar to other spotlights), but it does have a broader scope.

On top of that, I'm also adding at least one photo from the event, from the ones in Flickr - I'm assuming there is no legal limitation with that usage.

**Comment by fsmunoz** [comment]
@jberkus just to clarify, since after re-reading my comment I think it's a bit ambiguous: I welcome more reviewers for the content, but I wasn't aiming at changing the scope of the interview itself. We can certainly make another article with more people, even a round-table kind of thing, but I wouldn't change the structure of the current one.

**Comment by fsmunoz** [comment]
/title Add spotlight article on Kubernetes Contributor Summit

**Comment by fsmunoz** [comment]
/retitle Add spotlight article on Kubernetes Contributor Summit

**Comment by fsmunoz** [comment]
I've added a group photo from the Flickr set.

**Comment by fsmunoz** [comment]
Added https://github.com/kubernetes/website/pull/43775 for `website`.

**Comment by jberkus** [comment]
Approved, that way we don't have to change the date.

**Comment by sftim** [comment]
I think it's easier to line up both articles and then merge them once they're right. Maybe one day we'll have tooling to help with that.

**Pull request merged**
