### PR TITLE
KCSEU24: Adding Map to Social

### PR DESCRIPTION
**Pull request by chris-short**
Adding venue map provided by CNCF to the Social

### CODE REVIEW

**Review by nimbinatus — COMMENTED** [review]
/lgtm

**Comment by nimbinatus** [comment]
@chris-short do you need this up today, or do you want to wait for Natali?

**Comment by chris-short** [comment]
Not needed today, soon though.

**Comment by natalisucks** [comment]
sorry, here i am!
/approve

we'd like this today to send out the social email, so thanks @chris-short and @nimbinatus!

**Pull request merged**
