### PR TITLE
Created new top level Community section

### LINKED ISSUE #175: Dead link to mentoring initiatives in the Getting started doc
Hi,

looks like the link to the mentoring initiatives in the Getting started page is broken:

image

image

### LINKED ISSUE #201: Create new top level Community section
The community page will house our other documentation like our CoC, values, potentially mentoring etc.

To start, it should at a minimum have our CoC and values.

/kind feature

### PR DESCRIPTION
**Pull request by davideimola**
Hello folks!
This PR adds the new top-level Community section!

Fixes #201 
Fixes #175 

/cc @mrbobbytables

### CODE REVIEW

**Review by mrbobbytables — COMMENTED** [review]
Thank you! It looks great to me :)
/approve
/hold 
holding for other additional comments and reviews 👍

**Review by idvoretskyi — APPROVED** [review]
/lgtm

**Comment by nimbinatus** [comment]
Noticed the [welcome page](https://deploy-preview-214--kubernetes-contributor.netlify.app/welcome/) currently links out to the [GitHub list of SIGs](https://github.com/kubernetes/community/blob/master/sig-list.md) instead of the [community/community-groups page](https://deploy-preview-214--kubernetes-contributor.netlify.app/community/community-groups/). Would it be better to link internally to the site rather than sending someone to an external source now that it's in there?

**Pull request merged**
