### PR TITLE
blog: Fix image rendering

### LINKED ISSUE #305: Broken images in article K8s CI Bot Helper Job: automating "make update"
https://www.kubernetes.dev/blog/2022/03/15/k8s-triage-bot-helper-ci-job/ includes some images, but they don't work.

I also mentioned this as 
https://github.com/kubernetes/contributor-site/pull/293/files#r860838575 which provides some more context about where to fix this.#

/kind bug
/area blog

### PR DESCRIPTION
**Pull request by mk46**
This PR will fix the broken image in https://www.kubernetes.dev/blog/2022/03/15/k8s-triage-bot-helper-ci-job/
Fixes #305

### CODE REVIEW

**Comment by mk46** [comment]
Preview: https://deploy-preview-320--kubernetes-contributor.netlify.app/blog/2022/03/15/k8s-triage-bot-helper-ci-job/

**Review by mrbobbytables — CHANGES_REQUESTED** [review]
/hold
please do not move the images from their location. Hugo can reference files in the same dir as a page resource

**Comment by mk46** [comment]
> /hold please do not move the images from their location. Hugo can reference files in the same dir as a page resource

Sorry, Hugo is not rendering images from the same dir. Please see https://github.com/kubernetes/contributor-site/pull/293/files#r860838575.

faced a similar issue(https://github.com/kubernetes/website/issues/33204) in k/website too, which was fixed by moving images resources to `static` dir(https://github.com/kubernetes/website/pull/34918).

**Comment by mrbobbytables** [comment]
@mk46  here is an example - https://github.com/kubernetes/contributor-site/tree/master/content/en/blog/2020/contributing-to-the-development-guide

there are also other examples outside of the blog dir in the other areas of the site

**Comment by mk46** [comment]
should I remove `content/en/blog/2022/2022-03-15-k8s-triage-bot-helper-ci-job/K8s-ci-bot-make-update-helper.md`?
PTAL.
Thanks!!

**Comment by mrbobbytables** [comment]
The file should be renamed index.md and that should hopefully solve the issue.

**Review by mrbobbytables — COMMENTED** [review]
Thanks! That took care of it 👍 
https://deploy-preview-320--kubernetes-contributor.netlify.app/blog/2022/03/15/k8s-triage-bot-helper-ci-job/

/hold cancel
/lgtm
/approve

**Pull request merged**
