### PR TITLE
Fix/mentoring link

### LINKED ISSUE #175: Dead link to mentoring initiatives in the Getting started doc
Hi,

looks like the link to the mentoring initiatives in the Getting started page is broken:

image

image

### PR DESCRIPTION
**Pull request by davideimola**
Fixes #175 

I have removed the trailing whitespace in the main repository and added the content to the external sources.

### CODE REVIEW

**Review by mrbobbytables — COMMENTED** [review]
Heya, sorry I missed the comment on the issue asking about adding this. >_>

 I'd avoid bringing it over for now. While it has some events, its more an index of programs. 

We DO plan to add a community section (ref: https://github.com/kubernetes/contributor-site/issues/201) which I think would be more appropriate area. (If you'd like to create this, let me know and I guide).

The other thing we want to do to any content that is being ingested is add the hugo metadata header to the content in its original location so it makes sense while browsing and has the correct title/description. here is an example from the [github workflow doc](https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md) in the contributor guide:

```
---
title: "GitHub Workflow"
weight: 6
description: |
  An overview of the GitHub workflow used by the Kubernetes project. It includes
  some tips and suggestions on things such as keeping your local environment in
  sync with upstream and commit hygiene.
---
```

**Comment by davideimola** [comment]
> Heya, sorry I missed the comment on the issue asking about adding this. >_>
> 
Hey @mrbobbytables, not a problem! 

> I'd avoid bringing it over for now. While it has some events, its more an index of programs.
> 
Ok I understand, but I think it is not good to have a 404 page in the site!

> We DO plan to add a community section (ref: #201) which I think would be more appropriate area. (If you'd like to create this, let me know and I guide).
> 

Yes, sure I can handle it!

> The other thing we want to do to any content that is being ingested is add the hugo metadata header to the content in its original location so it makes sense while browsing and has the correct title/description. here is an example from the [github workflow doc](https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md) in the contributor guide:
> 
> ```
> ---
> title: "GitHub Workflow"
> weight: 6
> description: |
>   An overview of the GitHub workflow used by the Kubernetes project. It includes
>   some tips and suggestions on things such as keeping your local environment in
>   sync with upstream and commit hygiene.
> ---
> ```
Oh thanks, I did not have noticed that!

**Comment by mrbobbytables** [comment]
/hold 
Till the community section is in place 👍

**Pull request closed without merging**
