### PR TITLE
Bump release info page to 1.23

### PR DESCRIPTION
**Pull request by reylejano**
Bump release info page to 1.23.
The 1.23 release cycle starts today, Aug 23, 2021.
/cc @JamesLaverack @jrsapi @mkorbi @MonzElmasry 
/assign @mrbobbytables @cblecker

### CODE REVIEW

**Comment by reylejano** [comment]
/hold till Friday, August 27

schedule is finalized on Thursday, August 26

**Comment by cblecker** [comment]
Bob is out this week and I'm not an approver.
/unassign @cblecker @mrbobbytables 
/assign @idvoretskyi @castrojo

**Review by idvoretskyi — APPROVED** [review]
/lgtm

**Pull request merged**
