### PR TITLE
Add a blog post for contributor summit in shanghai

### PR DESCRIPTION
**Pull request by windsonsea**
By following suggestions in kubernetes/website#42999, add a blog for 2023 Kubernetes Contributor Summit in Shanghai.

cc @sftim

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
Sorry, the blog team didn't have capacity to review this in time. We're trying to grow the size of the blog team.

**Comment by sftim** [comment]
/close

We didn't have capacity to get this published.

**Comment by mrbobbytables** [comment]
If you want to post a summary blog of it, that'd be fine 👍

**Comment by pacoxu** [comment]
> If you want to post a summary blog of it, that'd be fine 👍 

Thanks. I will work on that after China's National Day holiday with @windsonsea.

**Pull request closed without merging**
