### PR TITLE
Bump release info page

### PR DESCRIPTION
**Pull request by mrbobbytables**
/assign @savitharaghunathan @annajung @erismaster @divya-mohan0209 @kikisdeliveryservice

### CODE REVIEW

**Comment by mrbobbytables** [comment]
/hold cancel
I think this is fine, we've done it for the past several releases, but missed updating this page earlier in the release cycle =/
Probably a note for the retro to make this a task once the readme is created.

**Comment by divya-mohan0209** [comment]
> /hold cancel
> I think this is fine, we've done it for the past several releases, but missed updating this page earlier in the release cycle =/
> Probably a note for the retro to make this a task once the readme is created.

@mrbobbytables : Would the RT Lead/Lead Shadows be the ones with the AI of doing this typically?

**Comment by mrbobbytables** [comment]
I think that'd be best. They'll know as soon as that readme is in a good enough state to publish

**Pull request merged**
