### PR TITLE
update current release to 1.24

### PR DESCRIPTION
**Pull request by salaxander**

### CODE REVIEW

**Comment by mrbobbytables** [comment]
inteeeerrreeesting, both CLAs say no :x

**Comment by salaxander** [comment]
Yeah it's because I did it on my work laptop 🙃. I'll get it sorted

**Comment by jberkus** [comment]
Approved, once we get the CLA situation fixed.

/approve
/lgtm

**Comment by salaxander** [comment]
reopening shortly

**Pull request closed without merging**
