### PR TITLE
blog: experience of LFX mentorship

### PR DESCRIPTION
**Pull request by mehabhalodiya**
Signed-off-by: mehabhalodiya <mehabhalodiya@gmail.com>

This PR adds the blog for my experience as an LFX mentee in CNCF Kubernetes: Gateway API (SIG Network). 
@Debanitrkl recommended to me that "Such type of content should also be posted on [k8s.dev](http://k8s.dev/)".

/cc @Debanitrkl

### CODE REVIEW

**Comment by jberkus** [comment]
@mehabhalodiya in order to make the experience of editing blog posts smoother for the writer, I'll ask you to do this via a new process.  Please paste your blog text into either Google Docs or Hackmd, and share a link with edit permissions in this PR.

**Comment by mehabhalodiya** [comment]
Let me know when all of the reviewers are done with suggesting changes in Google Doc. I will make those changes and do a single commit.

**Comment by kaslin** [comment]
We should probably ping the reviewers needed if more is needed?

**Comment by jberkus** [comment]
OK, I did another editorial pass.  There's a bunch of suggested edits on there -- mostly grammar stuff -- which you can just accept.  However, both Avinesh and I called out a few places where you could supply more information about your experience.  Please take a look at the comments.  Thanks!

**Comment by kaslin** [comment]
@mehabhalodiya have you seen the recommended edits?

**Comment by mehabhalodiya** [comment]
> @mehabhalodiya have you seen the recommended edits?

Oh ya @kaslin, I missed it out 🙁 
I am making the changes very soon and committing it here! Thank you for your patience 🙂

**Comment by kaslin** [comment]
@mehabhalodiya updates to status of this? Is it needed anymore?

**Comment by yashdev9274** [comment]
Hey @mehabhalodiya  as this PR is still open , is there anything I can help and work on here, although I'm looking in this projects if anything else is required.

**Comment by kaslin** [comment]
@mehabhalodiya pinging on this open blog post issue.

**Comment by kaslin** [comment]
@mehabhalodiya it's LFX season again (I think), so now would be timely to get this done! We're adding this to [our tracking board](https://github.com/orgs/kubernetes/projects/124/views/1). Let's see if we can push this to completion one way or another, @fsmunoz.

**Comment by mehabhalodiya** [comment]
Oh sorry @kaslin, I am missing this again and again. I am looking forward to completing it ASAP!

**Comment by kaslin** [comment]
We're gonna close this for now. Reopen if you make progress on it.
/close

**Pull request closed without merging**
