### PR TITLE
Fix double header

### PR DESCRIPTION
**Pull request by Harsh3363**

### CODE REVIEW

**Comment by sftim** [comment]
/retitle Fix double header

Relates to #433

**Review by sftim — CHANGES_REQUESTED** [review]
Thanks for the PR.

We can't accept this as it does not fix the issue.

You can
- look at the [preview](https://deploy-preview-443--kubernetes-contributor.netlify.app/community/values/)
- check out the code locally and then:
  `make container-server` (needs Linux / macOS)
  or run Hugo manually
  and visit the local preview: http://localhost:1313/community/values/

You'll see that there are still two similar headings.

If you'd like to ask for help learning about how to fix this, visit https://slack.k8s.io/ for an invitation to Kubernetes Slack, visit the `#kubernetes-new-contributors` channel and explain your request (for example: you might be asking for someone to volunteer to teach you more about the contribution process, or you might want to learn how static site generators like Hugo typically work).

**Comment by Harsh3363** [comment]
Sorry @sftim mistake from my side has been done in the PR I will make correct that and will make a PR after that. 
Thanks for responding

**Comment by sftim** [comment]
> Sorry @sftim mistake from my side has been done in the PR I will make correction in that and will make a PR after that.

I'm not able rightly to apprehend the confusion of ideas here. A fix is still welcome.

**Comment by mrbobbytables** [comment]
Going to go ahead and close, there doesn't look like there is any other follow up actions at this point.

/close

**Pull request closed without merging**
